name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          echo "No dependencies to install"
      - name: Check sorting
        run: python scripts/check_sorting.py
      - name: Compile scripts
        run: python -m py_compile scripts/*.py
